/* eslint-disable */
/* global WebImporter */
/**
 * Parser for contact-form (Puntos.net contact page).
 * The whole form (fields, validation, thank-you view) is generated by the
 * block JS, so the authored block is just an empty marker. Any optional
 * endpoint URL is carried on a Section Metadata "endpoint" row (handled
 * separately), not here.
 */
export default function parse(element, { document }) {
  const block = WebImporter.Blocks.createBlock(document, {
    name: 'contact-form',
    cells: [['']],
  });
  element.replaceWith(block);
}
